import { booleanEnv } from "@saleor/apps-shared/boolean-env";
import {
  newSecretKeyRuntimeEnv,
  newSecretKeyServerSchema,
} from "@saleor/apps-shared/secret-key-resolution";
import { formatEnvValidationError } from "@saleor/errors";
import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  client: {
    NEXT_PUBLIC_SENTRY_DSN: z.string().optional(),
  },
  server: {
    ALLOWED_DOMAIN_PATTERN: z.string().optional(),
    APL: z.enum(["saleor-cloud", "file", "upstash", "dynamodb"]).default("file"),
    APP_API_BASE_URL: z.string().optional(),
    APP_IFRAME_BASE_URL: z.string().optional(),
    APP_LOG_LEVEL: z.enum(["fatal", "error", "warn", "info", "debug", "trace"]).default("info"),
    AWS_ACCESS_KEY_ID: z.string().optional(),
    AWS_REGION: z.string().optional(),
    AWS_ROLE_ARN: z.string().optional(),
    AWS_SECRET_ACCESS_KEY: z.string().optional(),
    CONFIG_STORAGE_MODE: z.enum(["dynamodb", "upstash", "file"]).default("dynamodb"),
    CONFIG_STORAGE_FILE_PATH: z.string().optional(),
    DYNAMODB_MAIN_TABLE_NAME: z.string().optional(),
    DYNAMODB_REQUEST_TIMEOUT_MS: z.coerce.number().default(5_000),
    DYNAMODB_CONNECTION_TIMEOUT_MS: z.coerce.number().default(2_000),
    MANIFEST_APP_ID: z.string().default("com.arteze.ziina-app"),
    OTEL_ACCESS_TOKEN: z.string().optional(),
    OTEL_ENABLED: booleanEnv.defaultFalse,
    OTEL_SERVICE_NAME: z.string().default("saleor-app-payment-ziina"),
    PORT: z.coerce.number().default(3000),
    REPOSITORY_URL: z.string().optional(),
    SECRET_KEY: z.string(),
    UPSTASH_TOKEN: z.string().optional(),
    UPSTASH_URL: z.string().optional(),
    VERCEL_ENV: z.string().optional(),
    VERCEL_GIT_COMMIT_SHA: z.string().optional(),
    APP_NAME: z.string().default("Ziina"),
    ...newSecretKeyServerSchema,
  },
  shared: {
    NODE_ENV: z.enum(["development", "production", "test"]).default("development"),
    ENV: z.enum(["local", "development", "staging", "production"]).default("local"),
  },
  // we use the manual destruction here to validate if env variable is set inside turbo.json
  runtimeEnv: {
    ALLOWED_DOMAIN_PATTERN: process.env.ALLOWED_DOMAIN_PATTERN,
    APL: process.env.APL,
    APP_API_BASE_URL: process.env.APP_API_BASE_URL,
    APP_IFRAME_BASE_URL: process.env.APP_IFRAME_BASE_URL,
    APP_LOG_LEVEL: process.env.APP_LOG_LEVEL,
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_REGION: process.env.AWS_REGION,
    AWS_ROLE_ARN: process.env.AWS_ROLE_ARN,
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    CONFIG_STORAGE_MODE: process.env.CONFIG_STORAGE_MODE,
    CONFIG_STORAGE_FILE_PATH: process.env.CONFIG_STORAGE_FILE_PATH,
    DYNAMODB_MAIN_TABLE_NAME: process.env.DYNAMODB_MAIN_TABLE_NAME,
    DYNAMODB_REQUEST_TIMEOUT_MS: process.env.DYNAMODB_REQUEST_TIMEOUT_MS,
    DYNAMODB_CONNECTION_TIMEOUT_MS: process.env.DYNAMODB_CONNECTION_TIMEOUT_MS,
    ENV: process.env.ENV,
    MANIFEST_APP_ID: process.env.MANIFEST_APP_ID,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
    NODE_ENV: process.env.NODE_ENV,
    OTEL_ACCESS_TOKEN: process.env.OTEL_ACCESS_TOKEN,
    OTEL_ENABLED: process.env.OTEL_ENABLED,
    OTEL_SERVICE_NAME: process.env.OTEL_SERVICE_NAME,
    PORT: process.env.PORT,
    REPOSITORY_URL: process.env.REPOSITORY_URL,
    SECRET_KEY: process.env.SECRET_KEY,
    UPSTASH_TOKEN: process.env.UPSTASH_TOKEN,
    UPSTASH_URL: process.env.UPSTASH_URL,
    VERCEL_ENV: process.env.VERCEL_ENV,
    VERCEL_GIT_COMMIT_SHA: process.env.VERCEL_GIT_COMMIT_SHA,
    APP_NAME: process.env.APP_NAME,
    ...newSecretKeyRuntimeEnv,
  },
  isServer: typeof window === "undefined" || process.env.NODE_ENV === "test",
  onValidationError: formatEnvValidationError,
});
